version: '3.9'

services:
    ldap_api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8000
        env_file:
          - .env_sample
        extra_hosts:
            - host.docker.internal:host-gateway